DROP TABLE marque_tbl;
DROP TABLE piece_tbl;
DROP TABLE stock_tbl;
DROP TABLE technicien_tbl;
DROP TABLE configuration_tbl;
DROP TABLE piece_config_tbl;
DROP TABLE client_tbl;
DROP TABLE commande_config_tbl;
DROP TABLE config_tech_tbl;
